name: Cafe Sync

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get sha
      - run: curl https://api.github.com/repos/ElaWorkshop/awesome-cn-cafe/branches/master --silent | grep "sha" | head -n1 > src/sha 

      - name: Push new Cafe
      - uses: EndBug/add-and-commit@v4
        with:
          message: "chore: update source sha"
          add: "src/sha"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
